### ISSUE TITLE
!pom.xml is not up to date

### ISSUE THREAD

**Issue by m4gg1** [Almighty-Alpaca/JDA-Butler#62]
In the example pom.xml that you get when executing !pom.xml on discord both maven-compiler-plugin and maven-shade-plugin are not on the latest version. Could be irritating for new users since it seems like it'd throw an error. And I thought since you already create a new Hastebin file and get the version of the jda everytime the command is called it shouldn't be that much of an effort, but could be very useful. 
Thanks in advance! :)

**Comment by kantenkugel** [comment]
@m4gg1 Would you mind posting the up-to-date versions for those 2 plugins here?

They have to still work for java 8 btw

**Comment by m4gg1** [comment]
If its about the java version, not the maven plugin version, then why not add a comment telling you about which java version you have to use? ✌️

**Comment by kantenkugel** [comment]
What? Im just asking for the plugin versions to use and not to provide plugin versions that might not be compatible with java8 anymore (due to internal plugin changes)

**Comment by m4gg1** [comment]
For maven-compiler-plugin version 3.8.1 should work and for maven-shade-plugin it should be 3.2.4.. I haven’t checked the compatibility with java yet. I can do tomorrow. 

Edit: sorry I was being .. idk... weird.. in my last comment :)

**Comment by m4gg1** [comment]
I had success compiling using jdk version 1.8 261.
